# Generated by Django 6.0.4 on 2026-05-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tb_livros ADD COLUMN IF NOT EXISTS autor varchar(255);
            """,
            reverse_sql="""
                ALTER TABLE tb_livros DROP COLUMN IF EXISTS autor;
            """,
        ),
    ]
